"""Materialize ``eval/queries.toml`` from subject-pattern specs.

Reads :class:`QuerySpec` rows from ``eval/specs.toml`` and resolves
each predicate against the live DB. Specs live in a local TOML file
(``eval/specs.toml``) rather than this script so the patterns can
reference your *own* mailbox content without leaking it through git.
``eval/specs.toml`` is gitignored; ``eval/specs.example.toml`` is the
committed template — copy it over on first use.

Workflow:
  1. ``cp eval/specs.example.toml eval/specs.toml`` (first time only).
  2. Edit ``eval/specs.toml`` to add / tweak queries.
  3. ``uv run python scripts/materialize_queries.py``.
  4. Inspect ``eval/queries.toml``; trim any noisy matches.
  5. ``uv run python -m emailsearch.eval validate`` to sanity-check IDs.
  6. ``uv run python -m emailsearch.eval run`` to produce the report.
"""

from __future__ import annotations

import datetime as dt
import shutil
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from emailsearch.db.connection import open_connection

SPECS_PATH = Path("eval/specs.toml")
EXAMPLE_PATH = Path("eval/specs.example.toml")
OUT_PATH = Path("eval/queries.toml")


@dataclass
class QuerySpec:
    """One eval query plus the predicate that defines its ground truth.

    ``where_sql`` is appended to ``SELECT id FROM emails WHERE 1=1`` with
    ``params`` bound positionally — no string interpolation of values, so
    the script is safe against subject lines that contain quotes.

    ``cap`` bounds the relevant set so a wide pattern doesn't
    accidentally label hundreds of messages as relevant. Set to
    ``None`` to keep everything.
    """

    id: str
    text: str
    category: str
    description: str
    where_sql: str
    params: list[object] = field(default_factory=list)
    cap: int | None = 8
    order_by: str = "received_at DESC"


def _load_specs(path: Path) -> list[QuerySpec]:
    """Parse ``path`` into a list of QuerySpec. Schema is intentionally
    permissive — required fields are checked, optional ones default."""
    with path.open("rb") as f:
        data = tomllib.load(f)
    raw_specs = data.get("specs") or []
    if not isinstance(raw_specs, list):
        raise ValueError(f"{path}: top-level 'specs' must be an array of tables")
    out: list[QuerySpec] = []
    for i, raw in enumerate(raw_specs):
        try:
            out.append(
                QuerySpec(
                    id=raw["id"],
                    text=raw["text"],
                    category=raw["category"],
                    description=raw.get("description", ""),
                    where_sql=raw["where_sql"],
                    params=list(raw.get("params") or []),
                    cap=raw.get("cap", 8),
                    order_by=raw.get("order_by", "received_at DESC"),
                )
            )
        except KeyError as e:
            raise ValueError(
                f"{path}: spec #{i} missing required field {e!s}"
            ) from None
    return out


def materialize(specs: list[QuerySpec]) -> dict[str, list[dict[str, str]]]:
    """Run each spec's predicate against the live DB and collect matches."""
    conn = open_connection()
    try:
        out: dict[str, list[dict[str, str]]] = {}
        for spec in specs:
            sql = (
                f"SELECT id, subject, from_address FROM emails "
                f"WHERE 1=1 {spec.where_sql} "
                f"ORDER BY {spec.order_by}"
            )
            if spec.cap:
                sql += f" LIMIT {spec.cap}"
            rows = conn.execute(sql, spec.params).fetchall()
            out[spec.id] = [
                {"id": r["id"], "subject": r["subject"], "from": r["from_address"]}
                for r in rows
            ]
        return out
    finally:
        conn.close()


def to_toml(
    specs: list[QuerySpec],
    matches: dict[str, list[dict[str, str]]],
) -> str:
    """Render the matched specs as a queries.toml document.

    Subject snippets are deliberately omitted from inline comments so
    the queries.toml file contains only Message-IDs — minimizing how
    much email content leaks if the file is shared.
    """
    today = dt.date.today().isoformat()
    lines: list[str] = [
        "# Auto-generated by scripts/materialize_queries.py — feel free to hand-edit.",
        "# Each query's `relevant` list was selected by subject/sender pattern,",
        "# NOT by what the search system returns, so the metrics stay unbiased.",
        "# Subject text is intentionally NOT included in this file.",
        "",
        "version = 1",
        "",
        "[meta]",
        f'authored = "{today}"',
        'description = "EmailSearch quality eval — local pattern-curated relevance"',
        'notes = "Run: uv run python -m emailsearch.eval run"',
        "",
    ]
    for spec in specs:
        rows = matches.get(spec.id, [])
        lines.append("[[queries]]")
        lines.append(f'id = "{spec.id}"')
        lines.append(f"text = {_q(spec.text)}")
        lines.append(f'category = "{spec.category}"')
        lines.append(f"description = {_q(spec.description)}")
        if not rows:
            lines.append("# WARNING: predicate matched 0 rows — re-tune the pattern.")
            lines.append("relevant = []")
        else:
            lines.append(f"# matched {len(rows)} email(s)")
            lines.append("relevant = [")
            for r in rows:
                lines.append(f'    {_q(r["id"])},')
            lines.append("]")
        lines.append("")
    return "\n".join(lines) + "\n"


def _q(s: str) -> str:
    """TOML basic string with escaping for ``"`` and ``\\``."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ensure_specs_file() -> None:
    """Bootstrap ``eval/specs.toml`` from the example if it doesn't exist."""
    if SPECS_PATH.exists():
        return
    if not EXAMPLE_PATH.exists():
        print(
            f"ERROR: neither {SPECS_PATH} nor {EXAMPLE_PATH} exists. "
            "Create one before running.",
            file=sys.stderr,
        )
        sys.exit(2)
    SPECS_PATH.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(EXAMPLE_PATH, SPECS_PATH)
    print(f"bootstrapped {SPECS_PATH} from {EXAMPLE_PATH}")
    print("edit it to point at your own subject patterns, then re-run.")


def main() -> None:
    _ensure_specs_file()
    specs = _load_specs(SPECS_PATH)
    if not specs:
        print(f"ERROR: {SPECS_PATH} contains no [[specs]] entries.", file=sys.stderr)
        sys.exit(2)

    matches = materialize(specs)
    total = sum(len(v) for v in matches.values())
    empty = [sid for sid, rows in matches.items() if not rows]
    print(f"materialized {len(specs)} queries, {total} relevance IDs total")
    if empty:
        print(
            f"WARNING: {len(empty)} query/ies matched 0 emails: {empty}",
            file=sys.stderr,
        )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(to_toml(specs, matches), encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
